# .github/workflows/callables/build-java-service.yml
name: Java Build Callable

on:
  workflow_call:
    inputs:
      service-path:
        required: true
        type: string
      maven-goals:
        required: true
        type: string

jobs:
  build:
    name: Build Java Module
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Cache Maven
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2

      - name: Run Maven Build
        run: |
          cd ${{ inputs.service-path }}
          ./mvnw ${{ inputs.maven-goals }}

      - name: Check artifact
        run: |
          cd ${{ inputs.service-path }}
          if [[ ! -f target/app && ! -f target/app-runner && ! -f target/app.jar ]]; then
            echo \"Nenhum artefato padr√£o encontrado\" && exit 1
          fi

      - name: Docker Build & Push
        env:
          IMAGE_TAG: ghcr.io/${{ github.repository }}/$(basename ${{ inputs.service-path }})
        run: |
          cd ${{ inputs.service-path }}
          docker build -t $IMAGE_TAG:ci-${{ github.sha }} .
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          docker push $IMAGE_TAG:ci-${{ github.sha }}
